version: '2'
services:
  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=xy-inc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MAX_CONNECTIONS=300
    volumes:
      - ./scripts/docker-postgres-pois.sql:/docker-entrypoint-initdb.d/setup.sql